### ISSUE TITLE
Automatic identification of data types of string fields

### ISSUE THREAD

**Issue by ViliamLisy** [pevnak/JsonGrinder.jl#2]
If the JSONs contain a string field, which always includes integers, they are still extracted as String. A post-processing step checking for basic data types in string fields would be useful.

**Comment by racinmat** [comment]
What exactly should be covered? I don't want to make it too complex, because that should be part of preprocessing the json.
I'll definitely cover integers and floats in form of 1.2, 5.4, etc. Do you think it also makes sense to parse scientific notations?
