### ISSUE TITLE
Remove automatic joining of scalars?

### ISSUE THREAD

**Issue by racinmat** [pevnak/JsonGrinder.jl#39]
So far scalar values are concatenated together for performance sake.
Since for most domains this occasion is very sparse, and causes inconsistency between structure of extractor and model, the performance gain, which is negligible for our usecases, is not worth the problems with changing structure.

The best idea would probably be to keep it as an option, which can be turned on, but it would be turned off by default.

**Comment by racinmat** [comment]
it will be removed in JsonGrinder 2

**Comment by pevnak** [comment]
I think it is removed by now
