### ISSUE TITLE
Do we need `datatypes` in extractor

### ISSUE THREAD

**Issue by pevnak** [pevnak/JsonGrinder.jl#49]
This is the question. 
Do we need `datatypes` in extractor. I believe no in `ExtractScalar` and I wonder if in `ExtractString`, we should spit out string, on the end, this is governed `NGramMatrix` for extractor provided by us and others might do whatever they want.

**Comment by racinmat** [comment]
I'll think about that.

**Comment by pevnak** [comment]
No we do not
