### ISSUE TITLE
Better way to modify existing extractor.

### ISSUE THREAD

**Issue by racinmat** [pevnak/JsonGrinder.jl#98]
Currently we have e.g. in mutagenesis example https://github.com/CTUAvastLab/JsonGrinder.jl/blob/master/examples/mutagenesis.jl
following, cumbersome way of modifying current extractor after suggestion:
```julia
extractor[:atoms].item[:bonds].item.dict[:charge] = JsonGrinder.ExtractCategorical(sch[:atoms].items[:bonds].items[:charge])
```
which is lengthy and we need to specify the path twice.
Instead it would be nice to e.g. use lenses, but that would require us to have unique `code2lens`, which is not now, because the logic is: takt value under that code and match/return everything that is equal as element under that code.
Which is troublesome.

```julia
printtree(sch, trav=true)
printtree(extractor, trav=true)
sch["BK"]
code2lens(sch, "BK")
sch_lens = only(code2lens(sch, "BK"))
code2lens(extractor, "BK")
ext_lens = first(code2lens(extractor, "BK"))

using Setfield
get(sch, sch_lens)
get(extractor, ext_lens)
```
also the schema lens to extractor lens is not working now, I would expect this to work:
```julia
Setfield.set(extractor, ext_lens, JsonGrinder.ExtractCategorical(get(sch, sch_lens)))
```

But maybe it may suffice to have yet another parameter to suggestextractor, which woud be similar as `fsm` field in `reflectinmodel`, where one would pass dict of `path in schema` => suggestion of extractor baed on shema.
But the path used by string code is unstable and code changes based on another fields. Maybe putting lens there would be worth it?

**Comment by simonmandlik** [comment]
IMO, adding this to `suggestextractor` makes things too complicated, when this is a simple one liner:

```julia
sch = schema(...)
e = suggestextractor(sch)

using Accessors

set(e, code2lens(e, "BK"), ...)
```

But some examples may be added to the docs: https://github.com/CTUAvastLab/JsonGrinder.jl/issues/137
